package main

import (
	"database/sql"
	"fmt"
	. "models"

	_ "github.com/lib/pq"
)
var connectString string = "user=webchat password=web1234 dbname=webchatdb sslmode=disable"

func main(){
    db, err := sql.Open("postgres",connectString)

    if err != nil{
        panic(err)
    }
    defer db.Close()
    /*result, err := db.Exec(`
                            CREATE TABLE Products (
                                id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                model  varchar(30) NOT NULL,
                                company varchar(30) NOT NULL,
                                price integer NOT NULL
                            );
                            `)

    if err != nil{
        panic(err)
    }
    fmt.Println(result, "Таблица Products создалась! =)")*/

    // Insert
    result, err := db.Exec("INSERT INTO Products (model, company, price) values ('iPhone X', $1, $2)", "Apple", 72000)

    // Вместо $1 и $2 будут вставлены соответсвующие параметры, переданные в следующих параметрах функции db.Exec()


    if err != nil{
        panic(err)
    }
    fmt.Println(result.LastInsertId()) // Последний добавленный индекс (Он не поддерживается)
    fmt.Println(result.RowsAffected()) // Количество добавленные строк

    // Если обязательно нужно получить индекс добавленного объекта, то можно использовать метод db.QueryRow(), который
    // выполяет запрос и возвращает определенный объект.
    var id int
    db.QueryRow(`   insert into products (model, company, price)
                    values ('Mate 10 Pro', $1, $2)
                    returning id`, "Huawei", 35000).Scan(&id)
    fmt.Println(id)
    // В самом выражении sql находится подвыражение "returning id". И с помощью метода Scan() полученное значение
    // считывается в переменную id

    // Получение данных Select
    // Для получения данных применяется метод db.Query(), который возвращает набор строк, либо db.QueryRow(),
    // который возвращает одну строку
    rows, err := db.Query("select * from Products")
    if err != nil{
        panic(err)
    }
    defer rows.Close()

    products := []Product{}
    for rows.Next(){
        p := Product{}
        err := rows.Scan(&p.Id, &p.Model, &p.Company, &p.Price)
        if err != nil{
            fmt.Println(err)
            continue
        }
        products = append(products, p)
    }
    for _, p := range products{
        fmt.Println(p.Id, p.Model, p.Company, p.Price)
    }

    rows, err = db.Query("SELECT * FROM Products where price > $1", 70_000)
    products = []Product{}

    for rows.Next(){
        p := Product{}
        err = rows.Scan(&p.Id, &p.Model, &p.Company, &p.Price)
        if err != nil{
            panic(err)
        }
        fmt.Println(p.Id, p.Model, p.Company, p.Price)
    }

    // Обновление. Для обновления данных применяется метод Exec
    result, err = db.Exec("update Products set price = $1 where id = $2", 69_000, 1)
    if err != nil{
        panic(err)
    }
    fmt.Print("Количество обновленных строк: ") // Количество обновленных строк
    fmt.Println( result.RowsAffected())

    // Для удаления также применяется метод Exec
    result, err = db.Exec("delete from Products where Model = $1", "Mate 10 Pro")
    if err != nil{
        panic(err)
    }
    fmt.Print("Количество удалённых строк: ") // Количество удалённых строк
    fmt.Println( result.RowsAffected())

    result, err = db.Exec("delete from Products where Model = $1", "iPhone")
    if err != nil{
        panic(err)
    }
    fmt.Print("Количество удалённых строк: ") // Количество удалённых строк
    fmt.Println( result.RowsAffected())
}
